// A comprehensive list of countries with their codes, names, and flag emojis
export const countriesData = [
  { code: "af", name: "Afghanistan", flag: "🇦🇫", region: "Asia" },
  { code: "al", name: "Albania", flag: "🇦🇱", region: "Europe" },
  { code: "dz", name: "Algeria", flag: "🇩🇿", region: "Africa" },
  { code: "ad", name: "Andorra", flag: "🇦🇩", region: "Europe" },
  { code: "ao", name: "Angola", flag: "🇦🇴", region: "Africa" },
  { code: "ag", name: "Antigua and Barbuda", flag: "🇦🇬", region: "Americas" },
  { code: "ar", name: "Argentina", flag: "🇦🇷", region: "Americas" },
  { code: "am", name: "Armenia", flag: "🇦🇲", region: "Asia" },
  { code: "au", name: "Australia", flag: "🇦🇺", region: "Oceania" },
  { code: "at", name: "Austria", flag: "🇦🇹", region: "Europe" },
  { code: "az", name: "Azerbaijan", flag: "🇦🇿", region: "Asia" },
  { code: "bs", name: "Bahamas", flag: "🇧🇸", region: "Americas" },
  { code: "bh", name: "Bahrain", flag: "🇧🇭", region: "Asia" },
  { code: "bd", name: "Bangladesh", flag: "🇧🇩", region: "Asia" },
  { code: "bb", name: "Barbados", flag: "🇧🇧", region: "Americas" },
  { code: "by", name: "Belarus", flag: "🇧🇾", region: "Europe" },
  { code: "be", name: "Belgium", flag: "🇧🇪", region: "Europe" },
  { code: "bz", name: "Belize", flag: "🇧🇿", region: "Americas" },
  { code: "bj", name: "Benin", flag: "🇧🇯", region: "Africa" },
  { code: "bt", name: "Bhutan", flag: "🇧🇹", region: "Asia" },
  { code: "bo", name: "Bolivia", flag: "🇧🇴", region: "Americas" },
  { code: "ba", name: "Bosnia and Herzegovina", flag: "🇧🇦", region: "Europe" },
  { code: "bw", name: "Botswana", flag: "🇧🇼", region: "Africa" },
  { code: "br", name: "Brazil", flag: "🇧🇷", region: "Americas" },
  { code: "bn", name: "Brunei", flag: "🇧🇳", region: "Asia" },
  { code: "bg", name: "Bulgaria", flag: "🇧🇬", region: "Europe" },
  { code: "bf", name: "Burkina Faso", flag: "🇧🇫", region: "Africa" },
  { code: "bi", name: "Burundi", flag: "🇧🇮", region: "Africa" },
  { code: "cv", name: "Cabo Verde", flag: "🇨🇻", region: "Africa" },
  { code: "kh", name: "Cambodia", flag: "🇰🇭", region: "Asia" },
  { code: "cm", name: "Cameroon", flag: "🇨🇲", region: "Africa" },
  { code: "ca", name: "Canada", flag: "🇨🇦", region: "Americas" },
  { code: "cf", name: "Central African Republic", flag: "🇨🇫", region: "Africa" },
  { code: "td", name: "Chad", flag: "🇹🇩", region: "Africa" },
  { code: "cl", name: "Chile", flag: "🇨🇱", region: "Americas" },
  { code: "cn", name: "China", flag: "🇨🇳", region: "Asia" },
  { code: "co", name: "Colombia", flag: "🇨🇴", region: "Americas" },
  { code: "km", name: "Comoros", flag: "🇰🇲", region: "Africa" },
  { code: "cg", name: "Congo", flag: "🇨🇬", region: "Africa" },
  { code: "cd", name: "Congo (DRC)", flag: "🇨🇩", region: "Africa" },
  { code: "cr", name: "Costa Rica", flag: "🇨🇷", region: "Americas" },
  { code: "ci", name: "Côte d'Ivoire", flag: "🇨🇮", region: "Africa" },
  { code: "hr", name: "Croatia", flag: "🇭🇷", region: "Europe" },
  { code: "cu", name: "Cuba", flag: "🇨🇺", region: "Americas" },
  { code: "cy", name: "Cyprus", flag: "🇨🇾", region: "Europe" },
  { code: "cz", name: "Czech Republic", flag: "🇨🇿", region: "Europe" },
  { code: "dk", name: "Denmark", flag: "🇩🇰", region: "Europe" },
  { code: "dj", name: "Djibouti", flag: "🇩🇯", region: "Africa" },
  { code: "dm", name: "Dominica", flag: "🇩🇲", region: "Americas" },
  { code: "do", name: "Dominican Republic", flag: "🇩🇴", region: "Americas" },
  { code: "ec", name: "Ecuador", flag: "🇪🇨", region: "Americas" },
  { code: "eg", name: "Egypt", flag: "🇪🇬", region: "Africa" },
  { code: "sv", name: "El Salvador", flag: "🇸🇻", region: "Americas" },
  { code: "gq", name: "Equatorial Guinea", flag: "🇬🇶", region: "Africa" },
  { code: "er", name: "Eritrea", flag: "🇪🇷", region: "Africa" },
  { code: "ee", name: "Estonia", flag: "🇪🇪", region: "Europe" },
  { code: "sz", name: "Eswatini", flag: "🇸🇿", region: "Africa" },
  { code: "et", name: "Ethiopia", flag: "🇪🇹", region: "Africa" },
  { code: "fj", name: "Fiji", flag: "🇫🇯", region: "Oceania" },
  { code: "fi", name: "Finland", flag: "🇫🇮", region: "Europe" },
  { code: "fr", name: "France", flag: "🇫🇷", region: "Europe" },
  { code: "ga", name: "Gabon", flag: "🇬🇦", region: "Africa" },
  { code: "gm", name: "Gambia", flag: "🇬🇲", region: "Africa" },
  { code: "ge", name: "Georgia", flag: "🇬🇪", region: "Asia" },
  { code: "de", name: "Germany", flag: "🇩🇪", region: "Europe" },
  { code: "gh", name: "Ghana", flag: "🇬🇭", region: "Africa" },
  { code: "gr", name: "Greece", flag: "🇬🇷", region: "Europe" },
  { code: "gd", name: "Grenada", flag: "🇬🇩", region: "Americas" },
  { code: "gt", name: "Guatemala", flag: "🇬🇹", region: "Americas" },
  { code: "gn", name: "Guinea", flag: "🇬🇳", region: "Africa" },
  { code: "gw", name: "Guinea-Bissau", flag: "🇬🇼", region: "Africa" },
  { code: "gy", name: "Guyana", flag: "🇬🇾", region: "Americas" },
  { code: "ht", name: "Haiti", flag: "🇭🇹", region: "Americas" },
  { code: "hn", name: "Honduras", flag: "🇭🇳", region: "Americas" },
  { code: "hu", name: "Hungary", flag: "🇭🇺", region: "Europe" },
  { code: "is", name: "Iceland", flag: "🇮🇸", region: "Europe" },
  { code: "in", name: "India", flag: "🇮🇳", region: "Asia" },
  { code: "id", name: "Indonesia", flag: "🇮🇩", region: "Asia" },
  { code: "ir", name: "Iran", flag: "🇮🇷", region: "Asia" },
  { code: "iq", name: "Iraq", flag: "🇮🇶", region: "Asia" },
  { code: "ie", name: "Ireland", flag: "🇮🇪", region: "Europe" },
  { code: "il", name: "Israel", flag: "🇮🇱", region: "Asia" },
  { code: "it", name: "Italy", flag: "🇮🇹", region: "Europe" },
  { code: "jm", name: "Jamaica", flag: "🇯🇲", region: "Americas" },
  { code: "jp", name: "Japan", flag: "🇯🇵", region: "Asia" },
  { code: "jo", name: "Jordan", flag: "🇯🇴", region: "Asia" },
  { code: "kz", name: "Kazakhstan", flag: "🇰🇿", region: "Asia" },
  { code: "ke", name: "Kenya", flag: "🇰🇪", region: "Africa" },
  { code: "ki", name: "Kiribati", flag: "🇰🇮", region: "Oceania" },
  { code: "kp", name: "North Korea", flag: "🇰🇵", region: "Asia" },
  { code: "kr", name: "South Korea", flag: "🇰🇷", region: "Asia" },
  { code: "kw", name: "Kuwait", flag: "🇰🇼", region: "Asia" },
  { code: "kg", name: "Kyrgyzstan", flag: "🇰🇬", region: "Asia" },
  { code: "la", name: "Laos", flag: "🇱🇦", region: "Asia" },
  { code: "lv", name: "Latvia", flag: "🇱🇻", region: "Europe" },
  { code: "lb", name: "Lebanon", flag: "🇱🇧", region: "Asia" },
  { code: "ls", name: "Lesotho", flag: "🇱🇸", region: "Africa" },
  { code: "lr", name: "Liberia", flag: "🇱🇷", region: "Africa" },
  { code: "ly", name: "Libya", flag: "🇱🇾", region: "Africa" },
  { code: "li", name: "Liechtenstein", flag: "🇱🇮", region: "Europe" },
  { code: "lt", name: "Lithuania", flag: "🇱🇹", region: "Europe" },
  { code: "lu", name: "Luxembourg", flag: "🇱🇺", region: "Europe" },
  { code: "mg", name: "Madagascar", flag: "🇲🇬", region: "Africa" },
  { code: "mw", name: "Malawi", flag: "🇲🇼", region: "Africa" },
  { code: "my", name: "Malaysia", flag: "🇲🇾", region: "Asia" },
  { code: "mv", name: "Maldives", flag: "🇲🇻", region: "Asia" },
  { code: "ml", name: "Mali", flag: "🇲🇱", region: "Africa" },
  { code: "mt", name: "Malta", flag: "🇲🇹", region: "Europe" },
  { code: "mh", name: "Marshall Islands", flag: "🇲🇭", region: "Oceania" },
  { code: "mr", name: "Mauritania", flag: "🇲🇷", region: "Africa" },
  { code: "mu", name: "Mauritius", flag: "🇲🇺", region: "Africa" },
  { code: "mx", name: "Mexico", flag: "🇲🇽", region: "Americas" },
  { code: "fm", name: "Micronesia", flag: "🇫🇲", region: "Oceania" },
  { code: "md", name: "Moldova", flag: "🇲🇩", region: "Europe" },
  { code: "mc", name: "Monaco", flag: "🇲🇨", region: "Europe" },
  { code: "mn", name: "Mongolia", flag: "🇲🇳", region: "Asia" },
  { code: "me", name: "Montenegro", flag: "🇲🇪", region: "Europe" },
  { code: "ma", name: "Morocco", flag: "🇲🇦", region: "Africa" },
  { code: "mz", name: "Mozambique", flag: "🇲🇿", region: "Africa" },
  { code: "mm", name: "Myanmar", flag: "🇲🇲", region: "Asia" },
  { code: "na", name: "Namibia", flag: "🇳🇦", region: "Africa" },
  { code: "nr", name: "Nauru", flag: "🇳🇷", region: "Oceania" },
  { code: "np", name: "Nepal", flag: "🇳🇵", region: "Asia" },
  { code: "nl", name: "Netherlands", flag: "🇳🇱", region: "Europe" },
  { code: "nz", name: "New Zealand", flag: "🇳🇿", region: "Oceania" },
  { code: "ni", name: "Nicaragua", flag: "🇳🇮", region: "Americas" },
  { code: "ne", name: "Niger", flag: "🇳🇪", region: "Africa" },
  { code: "ng", name: "Nigeria", flag: "🇳🇬", region: "Africa" },
  { code: "mk", name: "North Macedonia", flag: "🇲🇰", region: "Europe" },
  { code: "no", name: "Norway", flag: "🇳🇴", region: "Europe" },
  { code: "om", name: "Oman", flag: "🇴🇲", region: "Asia" },
  { code: "pk", name: "Pakistan", flag: "🇵🇰", region: "Asia" },
  { code: "pw", name: "Palau", flag: "🇵🇼", region: "Oceania" },
  { code: "pa", name: "Panama", flag: "🇵🇦", region: "Americas" },
  { code: "pg", name: "Papua New Guinea", flag: "🇵🇬", region: "Oceania" },
  { code: "py", name: "Paraguay", flag: "🇵🇾", region: "Americas" },
  { code: "pe", name: "Peru", flag: "🇵🇪", region: "Americas" },
  { code: "ph", name: "Philippines", flag: "🇵🇭", region: "Asia" },
  { code: "pl", name: "Poland", flag: "🇵🇱", region: "Europe" },
  { code: "pt", name: "Portugal", flag: "🇵🇹", region: "Europe" },
  { code: "qa", name: "Qatar", flag: "🇶🇦", region: "Asia" },
  { code: "ro", name: "Romania", flag: "🇷🇴", region: "Europe" },
  { code: "ru", name: "Russia", flag: "🇷🇺", region: "Europe" },
  { code: "rw", name: "Rwanda", flag: "🇷🇼", region: "Africa" },
  { code: "kn", name: "Saint Kitts and Nevis", flag: "🇰🇳", region: "Americas" },
  { code: "lc", name: "Saint Lucia", flag: "🇱🇨", region: "Americas" },
  { code: "vc", name: "Saint Vincent and the Grenadines", flag: "🇻🇨", region: "Americas" },
  { code: "ws", name: "Samoa", flag: "🇼🇸", region: "Oceania" },
  { code: "sm", name: "San Marino", flag: "🇸🇲", region: "Europe" },
  { code: "st", name: "São Tomé and Príncipe", flag: "🇸🇹", region: "Africa" },
  { code: "sa", name: "Saudi Arabia", flag: "🇸🇦", region: "Asia" },
  { code: "sn", name: "Senegal", flag: "🇸🇳", region: "Africa" },
  { code: "rs", name: "Serbia", flag: "🇷🇸", region: "Europe" },
  { code: "sc", name: "Seychelles", flag: "🇸🇨", region: "Africa" },
  { code: "sl", name: "Sierra Leone", flag: "🇸🇱", region: "Africa" },
  { code: "sg", name: "Singapore", flag: "🇸🇬", region: "Asia" },
  { code: "sk", name: "Slovakia", flag: "🇸🇰", region: "Europe" },
  { code: "si", name: "Slovenia", flag: "🇸🇮", region: "Europe" },
  { code: "sb", name: "Solomon Islands", flag: "🇸🇧", region: "Oceania" },
  { code: "so", name: "Somalia", flag: "🇸🇴", region: "Africa" },
  { code: "za", name: "South Africa", flag: "🇿🇦", region: "Africa" },
  { code: "ss", name: "South Sudan", flag: "🇸🇸", region: "Africa" },
  { code: "es", name: "Spain", flag: "🇪🇸", region: "Europe" },
  { code: "lk", name: "Sri Lanka", flag: "🇱🇰", region: "Asia" },
  { code: "sd", name: "Sudan", flag: "🇸🇩", region: "Africa" },
  { code: "sr", name: "Suriname", flag: "🇸🇷", region: "Americas" },
  { code: "se", name: "Sweden", flag: "🇸🇪", region: "Europe" },
  { code: "ch", name: "Switzerland", flag: "🇨🇭", region: "Europe" },
  { code: "sy", name: "Syria", flag: "🇸🇾", region: "Asia" },
  { code: "tw", name: "Taiwan", flag: "🇹🇼", region: "Asia" },
  { code: "tj", name: "Tajikistan", flag: "🇹🇯", region: "Asia" },
  { code: "tz", name: "Tanzania", flag: "🇹🇿", region: "Africa" },
  { code: "th", name: "Thailand", flag: "🇹🇭", region: "Asia" },
  { code: "tl", name: "Timor-Leste", flag: "🇹🇱", region: "Asia" },
  { code: "tg", name: "Togo", flag: "🇹🇬", region: "Africa" },
  { code: "to", name: "Tonga", flag: "🇹🇴", region: "Oceania" },
  { code: "tt", name: "Trinidad and Tobago", flag: "🇹🇹", region: "Americas" },
  { code: "tn", name: "Tunisia", flag: "🇹🇳", region: "Africa" },
  { code: "tr", name: "Turkey", flag: "🇹🇷", region: "Asia" },
  { code: "tm", name: "Turkmenistan", flag: "🇹🇲", region: "Asia" },
  { code: "tv", name: "Tuvalu", flag: "🇹🇻", region: "Oceania" },
  { code: "ug", name: "Uganda", flag: "🇺🇬", region: "Africa" },
  { code: "ua", name: "Ukraine", flag: "🇺🇦", region: "Europe" },
  { code: "ae", name: "United Arab Emirates", flag: "🇦🇪", region: "Asia" },
  { code: "gb", name: "United Kingdom", flag: "🇬🇧", region: "Europe" },
  { code: "us", name: "United States", flag: "🇺🇸", region: "Americas" },
  { code: "uy", name: "Uruguay", flag: "🇺🇾", region: "Americas" },
  { code: "uz", name: "Uzbekistan", flag: "🇺🇿", region: "Asia" },
  { code: "vu", name: "Vanuatu", flag: "🇻🇺", region: "Oceania" },
  { code: "va", name: "Vatican City", flag: "🇻🇦", region: "Europe" },
  { code: "ve", name: "Venezuela", flag: "🇻🇪", region: "Americas" },
  { code: "vn", name: "Vietnam", flag: "🇻🇳", region: "Asia" },
  { code: "ye", name: "Yemen", flag: "🇾🇪", region: "Asia" },
  { code: "zm", name: "Zambia", flag: "🇿🇲", region: "Africa" },
  { code: "zw", name: "Zimbabwe", flag: "🇿🇼", region: "Africa" }
];
