-- Database Schema for VisaCheck App
-- This script will create the necessary tables and import the visa data

-- Create tables
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS countries (
  id SERIAL PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  flag TEXT NOT NULL,
  region TEXT
);

CREATE TABLE IF NOT EXISTS visa_requirements (
  id SERIAL PRIMARY KEY,
  from_country_code TEXT NOT NULL,
  to_country_code TEXT NOT NULL,
  status TEXT NOT NULL,
  duration TEXT,
  validity TEXT,
  processing TEXT,
  cost TEXT,
  notes TEXT,
  requirements JSONB,
  last_updated TEXT,
  CONSTRAINT visa_requirements_unique_combo UNIQUE (from_country_code, to_country_code)
);

CREATE TABLE IF NOT EXISTS search_history (
  id SERIAL PRIMARY KEY,
  from_country_code TEXT NOT NULL,
  to_country_code TEXT NOT NULL,
  searched_at TEXT NOT NULL
);

-- Import countries data
INSERT INTO countries (code, name, flag, region) VALUES
-- This is just a sample, the full list contains all countries
('af', 'Afghanistan', '🇦🇫', 'Asia'),
('al', 'Albania', '🇦🇱', 'Europe'),
('dz', 'Algeria', '🇩🇿', 'Africa'),
('ad', 'Andorra', '🇦🇩', 'Europe'),
('ao', 'Angola', '🇦🇴', 'Africa'),
('ag', 'Antigua and Barbuda', '🇦🇬', 'North America'),
('ar', 'Argentina', '🇦🇷', 'South America'),
('am', 'Armenia', '🇦🇲', 'Asia'),
('au', 'Australia', '🇦🇺', 'Oceania'),
('at', 'Austria', '🇦🇹', 'Europe'),
('az', 'Azerbaijan', '🇦🇿', 'Asia'),
('bs', 'Bahamas', '🇧🇸', 'North America'),
('bh', 'Bahrain', '🇧🇭', 'Asia'),
('bd', 'Bangladesh', '🇧🇩', 'Asia'),
('bb', 'Barbados', '🇧🇧', 'North America'),
('by', 'Belarus', '🇧🇾', 'Europe'),
('be', 'Belgium', '🇧🇪', 'Europe'),
('bz', 'Belize', '🇧🇿', 'North America'),
('bj', 'Benin', '🇧🇯', 'Africa'),
('bt', 'Bhutan', '🇧🇹', 'Asia'),
('bo', 'Bolivia', '🇧🇴', 'South America'),
('ba', 'Bosnia and Herzegovina', '🇧🇦', 'Europe'),
('bw', 'Botswana', '🇧🇼', 'Africa'),
('br', 'Brazil', '🇧🇷', 'South America'),
('bn', 'Brunei', '🇧🇳', 'Asia'),
('bg', 'Bulgaria', '🇧🇬', 'Europe'),
('bf', 'Burkina Faso', '🇧🇫', 'Africa'),
('bi', 'Burundi', '🇧🇮', 'Africa'),
('kh', 'Cambodia', '🇰🇭', 'Asia'),
('cm', 'Cameroon', '🇨🇲', 'Africa'),
('ca', 'Canada', '🇨🇦', 'North America'),
('cv', 'Cape Verde', '🇨🇻', 'Africa'),
('cf', 'Central African Republic', '🇨🇫', 'Africa'),
('td', 'Chad', '🇹🇩', 'Africa'),
('cl', 'Chile', '🇨🇱', 'South America'),
('cn', 'China', '🇨🇳', 'Asia'),
('co', 'Colombia', '🇨🇴', 'South America'),
('km', 'Comoros', '🇰🇲', 'Africa'),
('cg', 'Congo', '🇨🇬', 'Africa'),
('cd', 'Congo, Democratic Republic', '🇨🇩', 'Africa'),
('cr', 'Costa Rica', '🇨🇷', 'North America'),
('hr', 'Croatia', '🇭🇷', 'Europe'),
('cu', 'Cuba', '🇨🇺', 'North America'),
('cy', 'Cyprus', '🇨🇾', 'Europe'),
('cz', 'Czech Republic', '🇨🇿', 'Europe'),
('dk', 'Denmark', '🇩🇰', 'Europe'),
('dj', 'Djibouti', '🇩🇯', 'Africa'),
('dm', 'Dominica', '🇩🇲', 'North America'),
('do', 'Dominican Republic', '🇩🇴', 'North America'),
('ec', 'Ecuador', '🇪🇨', 'South America'),
('eg', 'Egypt', '🇪🇬', 'Africa'),
('sv', 'El Salvador', '🇸🇻', 'North America'),
('gq', 'Equatorial Guinea', '🇬🇶', 'Africa'),
('er', 'Eritrea', '🇪🇷', 'Africa'),
('ee', 'Estonia', '🇪🇪', 'Europe'),
('et', 'Ethiopia', '🇪🇹', 'Africa'),
('fj', 'Fiji', '🇫🇯', 'Oceania'),
('fi', 'Finland', '🇫🇮', 'Europe'),
('fr', 'France', '🇫🇷', 'Europe'),
('ga', 'Gabon', '🇬🇦', 'Africa'),
('gm', 'Gambia', '🇬🇲', 'Africa'),
('ge', 'Georgia', '🇬🇪', 'Asia'),
('de', 'Germany', '🇩🇪', 'Europe'),
('gh', 'Ghana', '🇬🇭', 'Africa'),
('gr', 'Greece', '🇬🇷', 'Europe'),
('gd', 'Grenada', '🇬🇩', 'North America'),
('gt', 'Guatemala', '🇬🇹', 'North America'),
('gn', 'Guinea', '🇬🇳', 'Africa'),
('gw', 'Guinea-Bissau', '🇬🇼', 'Africa'),
('gy', 'Guyana', '🇬🇾', 'South America'),
('ht', 'Haiti', '🇭🇹', 'North America'),
('hn', 'Honduras', '🇭🇳', 'North America'),
('hk', 'Hong Kong', '🇭🇰', 'Asia'),
('hu', 'Hungary', '🇭🇺', 'Europe'),
('is', 'Iceland', '🇮🇸', 'Europe'),
('in', 'India', '🇮🇳', 'Asia'),
('id', 'Indonesia', '🇮🇩', 'Asia'),
('ir', 'Iran', '🇮🇷', 'Asia'),
('iq', 'Iraq', '🇮🇶', 'Asia'),
('ie', 'Ireland', '🇮🇪', 'Europe'),
('il', 'Israel', '🇮🇱', 'Asia'),
('it', 'Italy', '🇮🇹', 'Europe'),
('ci', 'Ivory Coast', '🇨🇮', 'Africa'),
('jm', 'Jamaica', '🇯🇲', 'North America'),
('jp', 'Japan', '🇯🇵', 'Asia'),
('jo', 'Jordan', '🇯🇴', 'Asia'),
('kz', 'Kazakhstan', '🇰🇿', 'Asia'),
('ke', 'Kenya', '🇰🇪', 'Africa'),
('ki', 'Kiribati', '🇰🇮', 'Oceania'),
('kp', 'North Korea', '🇰🇵', 'Asia'),
('kr', 'South Korea', '🇰🇷', 'Asia'),
('kw', 'Kuwait', '🇰🇼', 'Asia'),
('kg', 'Kyrgyzstan', '🇰🇬', 'Asia'),
('la', 'Laos', '🇱🇦', 'Asia'),
('lv', 'Latvia', '🇱🇻', 'Europe'),
('lb', 'Lebanon', '🇱🇧', 'Asia'),
('ls', 'Lesotho', '🇱🇸', 'Africa'),
('lr', 'Liberia', '🇱🇷', 'Africa'),
('ly', 'Libya', '🇱🇾', 'Africa'),
('li', 'Liechtenstein', '🇱🇮', 'Europe'),
('lt', 'Lithuania', '🇱🇹', 'Europe'),
('lu', 'Luxembourg', '🇱🇺', 'Europe'),
('mo', 'Macau', '🇲🇴', 'Asia'),
('mk', 'North Macedonia', '🇲🇰', 'Europe'),
('mg', 'Madagascar', '🇲🇬', 'Africa'),
('mw', 'Malawi', '🇲🇼', 'Africa'),
('my', 'Malaysia', '🇲🇾', 'Asia'),
('mv', 'Maldives', '🇲🇻', 'Asia'),
('ml', 'Mali', '🇲🇱', 'Africa'),
('mt', 'Malta', '🇲🇹', 'Europe'),
('mh', 'Marshall Islands', '🇲🇭', 'Oceania'),
('mr', 'Mauritania', '🇲🇷', 'Africa'),
('mu', 'Mauritius', '🇲🇺', 'Africa'),
('mx', 'Mexico', '🇲🇽', 'North America'),
('fm', 'Micronesia', '🇫🇲', 'Oceania'),
('md', 'Moldova', '🇲🇩', 'Europe'),
('mc', 'Monaco', '🇲🇨', 'Europe'),
('mn', 'Mongolia', '🇲🇳', 'Asia'),
('me', 'Montenegro', '🇲🇪', 'Europe'),
('ma', 'Morocco', '🇲🇦', 'Africa'),
('mz', 'Mozambique', '🇲🇿', 'Africa'),
('mm', 'Myanmar', '🇲🇲', 'Asia'),
('na', 'Namibia', '🇳🇦', 'Africa'),
('nr', 'Nauru', '🇳🇷', 'Oceania'),
('np', 'Nepal', '🇳🇵', 'Asia'),
('nl', 'Netherlands', '🇳🇱', 'Europe'),
('nz', 'New Zealand', '🇳🇿', 'Oceania'),
('ni', 'Nicaragua', '🇳🇮', 'North America'),
('ne', 'Niger', '🇳🇪', 'Africa'),
('ng', 'Nigeria', '🇳🇬', 'Africa'),
('no', 'Norway', '🇳🇴', 'Europe'),
('om', 'Oman', '🇴🇲', 'Asia'),
('pk', 'Pakistan', '🇵🇰', 'Asia'),
('pw', 'Palau', '🇵🇼', 'Oceania'),
('ps', 'Palestine', '🇵🇸', 'Asia'),
('pa', 'Panama', '🇵🇦', 'North America'),
('pg', 'Papua New Guinea', '🇵🇬', 'Oceania'),
('py', 'Paraguay', '🇵🇾', 'South America'),
('pe', 'Peru', '🇵🇪', 'South America'),
('ph', 'Philippines', '🇵🇭', 'Asia'),
('pl', 'Poland', '🇵🇱', 'Europe'),
('pt', 'Portugal', '🇵🇹', 'Europe'),
('qa', 'Qatar', '🇶🇦', 'Asia'),
('ro', 'Romania', '🇷🇴', 'Europe'),
('ru', 'Russia', '🇷🇺', 'Europe'),
('rw', 'Rwanda', '🇷🇼', 'Africa'),
('kn', 'Saint Kitts and Nevis', '🇰🇳', 'North America'),
('lc', 'Saint Lucia', '🇱🇨', 'North America'),
('vc', 'Saint Vincent and the Grenadines', '🇻🇨', 'North America'),
('ws', 'Samoa', '🇼🇸', 'Oceania'),
('sm', 'San Marino', '🇸🇲', 'Europe'),
('st', 'Sao Tome and Principe', '🇸🇹', 'Africa'),
('sa', 'Saudi Arabia', '🇸🇦', 'Asia'),
('sn', 'Senegal', '🇸🇳', 'Africa'),
('rs', 'Serbia', '🇷🇸', 'Europe'),
('sc', 'Seychelles', '🇸🇨', 'Africa'),
('sl', 'Sierra Leone', '🇸🇱', 'Africa'),
('sg', 'Singapore', '🇸🇬', 'Asia'),
('sk', 'Slovakia', '🇸🇰', 'Europe'),
('si', 'Slovenia', '🇸🇮', 'Europe'),
('sb', 'Solomon Islands', '🇸🇧', 'Oceania'),
('so', 'Somalia', '🇸🇴', 'Africa'),
('za', 'South Africa', '🇿🇦', 'Africa'),
('ss', 'South Sudan', '🇸🇸', 'Africa'),
('es', 'Spain', '🇪🇸', 'Europe'),
('lk', 'Sri Lanka', '🇱🇰', 'Asia'),
('sd', 'Sudan', '🇸🇩', 'Africa'),
('sr', 'Suriname', '🇸🇷', 'South America'),
('sz', 'Eswatini', '🇸🇿', 'Africa'),
('se', 'Sweden', '🇸🇪', 'Europe'),
('ch', 'Switzerland', '🇨🇭', 'Europe'),
('sy', 'Syria', '🇸🇾', 'Asia'),
('tw', 'Taiwan', '🇹🇼', 'Asia'),
('tj', 'Tajikistan', '🇹🇯', 'Asia'),
('tz', 'Tanzania', '🇹🇿', 'Africa'),
('th', 'Thailand', '🇹🇭', 'Asia'),
('tl', 'Timor-Leste', '🇹🇱', 'Asia'),
('tg', 'Togo', '🇹🇬', 'Africa'),
('to', 'Tonga', '🇹🇴', 'Oceania'),
('tt', 'Trinidad and Tobago', '🇹🇹', 'North America'),
('tn', 'Tunisia', '🇹🇳', 'Africa'),
('tr', 'Turkey', '🇹🇷', 'Asia'),
('tm', 'Turkmenistan', '🇹🇲', 'Asia'),
('tv', 'Tuvalu', '🇹🇻', 'Oceania'),
('ug', 'Uganda', '🇺🇬', 'Africa'),
('ua', 'Ukraine', '🇺🇦', 'Europe'),
('ae', 'United Arab Emirates', '🇦🇪', 'Asia'),
('gb', 'United Kingdom', '🇬🇧', 'Europe'),
('us', 'United States', '🇺🇸', 'North America'),
('uy', 'Uruguay', '🇺🇾', 'South America'),
('uz', 'Uzbekistan', '🇺🇿', 'Asia'),
('vu', 'Vanuatu', '🇻🇺', 'Oceania'),
('va', 'Vatican City', '🇻🇦', 'Europe'),
('ve', 'Venezuela', '🇻🇪', 'South America'),
('vn', 'Vietnam', '🇻🇳', 'Asia'),
('ye', 'Yemen', '🇾🇪', 'Asia'),
('zm', 'Zambia', '🇿🇲', 'Africa'),
('zw', 'Zimbabwe', '🇿🇼', 'Africa');

-- Spanish passport requirements (sample)
INSERT INTO visa_requirements (from_country_code, to_country_code, status, duration, validity, processing, cost, notes, requirements, last_updated)
VALUES 
('es', 'us', 'visa-free', '90 days', 'Multiple entry', 'ESTA required', '$21 ESTA fee', 'Spanish passport holders can enter the USA under the Visa Waiver Program (VWP) for up to 90 days for tourism or business. An approved ESTA is required before travel.', '["Valid passport with at least 6 months validity","Approved ESTA (Electronic System for Travel Authorization)","Proof of onward travel","Sufficient funds for stay"]'::jsonb, '2023-10-15'),

('es', 'ca', 'visa-free', '180 days', 'Multiple entry', 'eTA required', 'CAD$7 eTA fee', 'Spanish citizens need an Electronic Travel Authorization (eTA) to fly to Canada. No visa required for stays up to 6 months.', '["Valid passport", "Approved eTA", "Proof of sufficient funds"]'::jsonb, '2023-10-15'),

('es', 'gb', 'visa-free', '6 months', 'Multiple entry', 'N/A', 'Free', 'Spanish citizens can visit the UK for up to 6 months without a visa for tourism, business meetings, or visiting friends/family.', '["Valid passport"]'::jsonb, '2023-11-01'),

('es', 'fr', 'visa-free', 'Unlimited', 'N/A', 'N/A', 'Free', 'As an EU citizen, Spanish passport holders have the right to free movement within the European Union.', '["Valid passport or national ID card"]'::jsonb, '2023-10-10'),

('es', 'de', 'visa-free', 'Unlimited', 'N/A', 'N/A', 'Free', 'As an EU citizen, Spanish passport holders have the right to free movement within the European Union.', '["Valid passport or national ID card"]'::jsonb, '2023-10-10'),

('es', 'it', 'visa-free', 'Unlimited', 'N/A', 'N/A', 'Free', 'As an EU citizen, Spanish passport holders have the right to free movement within the European Union.', '["Valid passport or national ID card"]'::jsonb, '2023-10-10'),

('es', 'au', 'e-visa', '90 days', 'Multiple entry', '1-3 business days', 'AUD$20', 'Spanish citizens need to apply for an ETA (Electronic Travel Authority) before traveling to Australia.', '["Valid passport with at least 6 months validity","Online ETA application"]'::jsonb, '2023-07-15'),

('es', 'jp', 'visa-free', '90 days', 'Multiple entry', 'N/A', 'Free', 'Spanish citizens can visit Japan for tourism, business, or visiting friends/relatives without a visa for up to 90 days.', '["Valid passport", "Proof of onward travel", "Sufficient funds for stay"]'::jsonb, '2023-07-15'),

('es', 'cn', 'visa-required', 'Varies by visa type', 'Single or multiple entry', '4-7 business days', '€126.55', 'Spanish citizens need to apply for a visa before traveling to China. Different visa types available depending on the purpose of visit.', '["Valid passport with at least 6 months validity and blank pages", "Completed visa application form", "Passport photo meeting requirements", "Proof of travel arrangements", "Invitation letter for some visa types"]'::jsonb, '2023-06-12'),

('es', 'th', 'visa-free', '30 days', 'Single entry', 'N/A', 'Free', 'Spanish passport holders can enter Thailand for tourism without a visa for up to 30 days (when arriving by air).', '["Valid passport with at least 6 months validity", "Proof of onward travel", "Proof of sufficient funds (20,000 THB per person)"]'::jsonb, '2023-05-20');

-- Add default fallback entry
INSERT INTO visa_requirements (from_country_code, to_country_code, status, duration, validity, processing, cost, notes, requirements, last_updated)
VALUES 
('default', 'default', 'unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'No specific visa information available. Please consult the embassy or consulate of the destination country for accurate visa requirements.', '["Valid passport with at least 6 months validity", "Proof of onward travel", "Proof of sufficient funds", "Check with embassy for detailed requirements"]'::jsonb, '2023-11-01');